scalar DateTime
scalar JSON

enum BookStatus {
  AVAILABLE
  ON_LOAN
  WITHDRAWN
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

enum SortDirection {
  ASC
  DESC
}

input IDFilter {
  eq: ID
  ne: ID
  in: [ID!]
}

input StringFilter {
  eq: String
  ne: String
  in: [String!]
  contains: String
  startsWith: String
}

input BookStatusFilter {
  eq: BookStatus
  ne: BookStatus
  in: [BookStatus!]
}

type Book {
  id: ID!
  isbn: String
  title: String!
  author: String!
  status: BookStatus!
  borrower: Member
  owner: Member
}

type BookConnection {
  edges: [BookEdge!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type BookEdge {
  node: Book!
  cursor: String!
}

input BookFilter {
  id: IDFilter
  isbn: StringFilter
  title: StringFilter
  author: StringFilter
  status: BookStatusFilter
  AND: [BookFilter!]
  OR: [BookFilter!]
  NOT: BookFilter
}

input BookOrderBy {
  id: SortDirection
  isbn: SortDirection
  title: SortDirection
  author: SortDirection
  status: SortDirection
}

type SearchHit_Book {
  node: Book!
  score: Float!
}

type SearchResult_Book {
  hits: [SearchHit_Book!]!
  totalCount: Int!
  hasNextPage: Boolean!
}

type Member {
  id: ID!
  memberNumber: String
  name: String!
  email: String
  books: [Book!]!
  ownedBooks: [Book!]!
}

type MemberConnection {
  edges: [MemberEdge!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

type MemberEdge {
  node: Member!
  cursor: String!
}

input MemberFilter {
  id: IDFilter
  memberNumber: StringFilter
  name: StringFilter
  email: StringFilter
  AND: [MemberFilter!]
  OR: [MemberFilter!]
  NOT: MemberFilter
}

input MemberOrderBy {
  id: SortDirection
  memberNumber: SortDirection
  name: SortDirection
  email: SortDirection
}

type SearchHit_Member {
  node: Member!
  score: Float!
}

type SearchResult_Member {
  hits: [SearchHit_Member!]!
  totalCount: Int!
  hasNextPage: Boolean!
}

enum AggregateFunction {
  COUNT
  SUM
  AVG
  MIN
  MAX
}

input AggregateFieldInput {
  field: String!
  fn: AggregateFunction!
  alias: String
}

type AggregateGroup {
  keys: JSON!
  values: JSON!
}

type AggregateResult {
  groups: [AggregateGroup!]!
  totalGroups: Int!
}

type Query {
  book(id: ID!): Book
  books(filter: BookFilter, orderBy: BookOrderBy, first: Int, after: String, last: Int, before: String): BookConnection!
  bookAggregate(filter: BookFilter, groupBy: [String!], fields: [AggregateFieldInput!]!): AggregateResult!
  searchBooks(query: String!, fields: [String!], filter: BookFilter, first: Int, after: String): SearchResult_Book!
  member(id: ID!): Member
  members(filter: MemberFilter, orderBy: MemberOrderBy, first: Int, after: String, last: Int, before: String): MemberConnection!
  memberAggregate(filter: MemberFilter, groupBy: [String!], fields: [AggregateFieldInput!]!): AggregateResult!
  searchMembers(query: String!, fields: [String!], filter: MemberFilter, first: Int, after: String): SearchResult_Member!
}
